
name: Componly project sdasdaasd

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspaces:
          - ./

    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 18

      - name: Install dependencies
        id: install-dependencies
        run: |
          echo -e "\n@componly:registry=https://npm.pkg.github.com/" >> .npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.COMPONLY_NPM_AUTH_TOKEN }} >> .npmrc
          if [[ "${{ matrix.workspaces}}" != "empty" ]]; then
              pwd
              pushd ${{ matrix.workspaces }}
              echo "workspace : -----> ${{ matrix.workspaces}}"
              yarn install --prefer-offline && yarn add @componly/core  @componly/schemas  @componly/cli axios form-data  -D --prefer-offline
              popd
          else
              echo "No workspaces to install. Running 'yarn install' in the root directory."
              yarn install --prefer-offline && yarn add @componly/core  @componly/schemas  @componly/cli axios form-data  -D --prefer-offline
          fi
          echo -e "\n@componly:registry=https://npm.pkg.github.com/" >> .npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.COMPONLY_NPM_AUTH_TOKEN }} >> .npmrc
          if [[ "${{ matrix.workspaces}}" != "empty" ]]; then
              pwd
              pushd ${{ matrix.workspaces }}
              yarn install && yarn add @componly/core  @componly/schemas  @componly/cli axios -D 
              popd
          else
              echo "No workspaces to install. Running 'yarn install' in the root directory."
              yarn install && yarn add @componly/core  @componly/schemas  @componly/cli axios -D 
          fi
    
      - name: scan
        id: componly-scan
        env:
          COMMIT_NAME: ${{ github.event.head_commit.message }}
          RUN_ID: ${{ github.run_id }}
          COMMIT_HASH: ${{ github.sha }}
          STEP_OUTCOME: ${{ steps.componly-scan.outcome }}
          JOB_NAME: ${{ github.job }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_NAME: ${{ github.workflow }}
          COMPONLY_BACKEND_URL: https://backend-production-e808.up.railway.app
          COMPONLY_CLI_ENV: development
        run: |
          ls -a 
          cd  ${{ matrix.workspaces }}   
          npx componly scan --cli-id=${{secrets.COMPONLY_API_KEY}} --cli-password="${{secrets.COMPONLY_API_SECRET}}" --config-path ./   --project  ./

